version: "3.8"

services:
  aws:
    image: amazon/aws-cli
    volumes:
      - $PWD:/app
    working_dir: /app 
    environment: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
  terraform:
    image: terraform
    build:
      context: .
      dockerfile: ./docker/dockerfiles/terraform.dockerfile
    volumes:
      - $PWD:/app
    working_dir: /app   
    environment: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_KEY
      - AWS_REGION
    